name: Invalidations
on: [push]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
    # Create check run
    - uses: octokit/request-action@v2.x
      id: create_check_run
      name: Create check for report
      with:
        route: POST /repos/:repository/check-runs
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
          previews: 
            - antiope
        name: "report"
        status: "in_progress"
        head_sha: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
    - uses: julia-actions/setup-julia@v1
      with:
        version: 'nightly'
        
    - uses: actions/checkout@v2
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-invalidations@v1
      id: invs_pr
    
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-invalidations@v1
      id: invs_master
    
    - name: Print invalidation report
      id: report
      run: |
        echo "Invalidations on master: ${{ steps.invs_master.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps)"
        echo "This branch: ${{ steps.invs_pr.outputs.total }} (${{ steps.invs_pr.outputs.deps }} via deps)"
      shell: bash  
      
    # Update check run to completed, succesful status
    - uses: octokit/request-action@v2.x
      if: ${{ steps.invs_pr.outputs.total }} > ${{ steps.invs_master.outputs.total }}
      id: update_check_run_failure
      with:
        route: PATCH /repos/:repository/check-runs/:check_run_id
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
          previews: 
            - antiope
        check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
        name: "report"
        conclusion: "failure"
        status: "completed"
        output: |
          title: "${{ steps.invs_pr.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps) vs. ${{ steps.invs_master.outputs.total }} on master"
          summary: "PR increases number of invalidations"
          text: "Invalidations on master: ${{ steps.invs_master.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps)\nThis branch: ${{ steps.invs_pr.outputs.total }} (${{ steps.invs_pr.outputs.deps }} via deps)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: octokit/request-action@v2.x
      if: ${{ steps.invs_pr.outputs.total }} <= ${{ steps.invs_master.outputs.total }}
      id: update_check_run_success
      with:
        route: PATCH /repos/:repository/check-runs/:check_run_id
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
          previews: 
            - antiope
        check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
        name: "report"
        conclusion: "success"
        status: "completed"
        output: |
          title: "${{ steps.invs_pr.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps) vs. ${{ steps.invs_master.outputs.total }} on master"
          summary: "PR is unchanged or reduces number of invalidations"
          text: "Invalidations on master: ${{ steps.invs_master.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps)\nThis branch: ${{ steps.invs_pr.outputs.total }} (${{ steps.invs_pr.outputs.deps }} via deps)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: octokit/request-action@v2.x
      if: ${{ failure() }}
      id: update_check_run_error
      with:
        route: PATCH /repos/:repository/check-runs/:check_run_id
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
          previews: 
            - antiope
        check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
        name: "report"
        conclusion: "neutral"
        status: "completed"
        output: |
          title: "Evaluating invalidations failed"
          summary: "Evaluating invalidations failed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: exit 1
      if: ${{ failure() }}
