name: Invalidations
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
    - uses: julia-actions/setup-julia@v1
      with:
        version: 'nightly'
    - uses: actions/checkout@v2
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-invalidations@v1
      id: invs_pr
    
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-invalidations@v1
      id: invs_master
    
    - name: Report invalidation counts
      run: |
        echo "Invalidations on master: ${{ steps.invs_master.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps)"
        echo "This branch: ${{ steps.invs_pr.outputs.total }} (${{ steps.invs_pr.outputs.deps }} via deps)"
      shell: bash
    - name: Report invalidations on check conclusion (pass)
      uses: dflydev/check-runs-action@v1
      if: ${{ steps.invs_pr.outputs.total <= steps.invs_master.outputs.total }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: '{"title":"${{ steps.invs_pr.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps) vs. ${{ steps.invs_master.outputs.total }} on master"}'
        conclusion: success
    - name: Report invalidations on check conclusion (fail)
      uses: dflydev/check-runs-action@v1
      if: ${{ steps.invs_pr.outputs.total > steps.invs_master.outputs.total }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: '{"title":"${{ steps.invs_pr.outputs.total }} (${{ steps.invs_master.outputs.deps }} via deps) vs. ${{ steps.invs_master.outputs.total }} on master"}'
        conclusion: failure
